# BASE UI
ColorColumn: '- bgDark' # used for the columns set with 'colorcolumn'
Conceal: 'gray - i' # placeholders for concealed text (see 'conceallevel')
Cursor: 'salmon grayDark' # the character under the cursor 
CursorIM: 'salmon grayDark' # like Cursor, but used when in IME mode
CursorColumn: '- white' # column the cursor is in when 'cursorcolumn' is set
CursorLine: '- white' # line the cursor is in when 'cursorline' is set
CursorLineNr: 'textEmphasis' # LineNr with 'cursorline'/'relativenumber' set
Directory: 'green' # directory names (and other special names in listings)
DiffAdd: '- greenLight' # diff mode: added line
DiffChange: '- yellowDark' # diff mode: changed line
DiffDelete: '- red' # diff mode: deleted line
DiffText: '- - r' # diff mode: changed text within a line
ErrorMsg: 'red white' # error messages on the command line
VertSplit: 'bgDark bgDark' # column separating vertical splits
Folded: 'textLight' # line used for closed folds
FoldColumn: 'purpleDark purpleLight' # 'foldcolumn'
SignColumn: 'purpleDark purpleLight' # column where |signs| are displayed
IncSearch: 'textDark yellow u' # 'incsearch' and ":s///c" replacement highlighting
LineNr: 'textLight' # line number
MatchParen: '- grayDark' # paired bracket and its match
ModeMsg: 'text grayLight' # 'showmode' message (e.g., "-- INSERT --")
MoreMsg: 'text grayLight' # see more-prompt
NonText: 'gray - i' # characters that aren't really in the text (e.g. invisible)
Normal: 'text bg' # normal text
PMenu: 'textLight yellowDark' # popup menu: normal item
PMenuSel: 'white purpleDark' # popup menu: selected item
PmenuSbar: 'white white' # popup menu: scrollbar
PmenuThumb: 'purpleDark purpleDark' # popup menu: thumb of the scrollbar
Question: 'grayDark' # |hit-enter| prompt and yes/no questions
Search: 'textDark yellowLight u' # last search pattern highlighting (see 'hlsearch')
SpecialKey: 'gray - i' # keys listed with ":map", chars in 'listchars'
SpellBad: 'red - c' # word not recognized by the spellchecker
SpellLocal: 'red - c' # word spellchecker recognizes as from another region
SpellCap: 'purple - c' # word that should start with a capital
SpellRare: 'yellow - c' # word the spellchecker recognizes as hardly used
StatusLine: 'textLight grayLight' # status line of current window
                                  # shows "^^^" chars when same as StatusLineNC
StatusLineNC: 'textLight bgDark' # unfocused window status line
TabLine: 'text grayLight' # non-active tab page label
TabLineFill: 'gray grayLight' # where there are no labels
TabLineSel: 'grayDark bg' # active tab page label
Title: 'purpleDark - b' # titles for output from ":set all", ":autocmd" etc
Visual: 'purpleDark gray' # visual mode selection
VisualNOS: 'purpleDark gray' # Visual when vim is "Not Owning the Selection" (X11)
WarningMsg: 'orange' # warning messages
WildMenu: 'grayDark purple' # current 'wildmenu' selection (bg is StatusLine)
# BASE SYNTAX
Comment: 'textLight - i' # any comment
Constant: 'grayDark' # any constant
String: 'blue bgDark' # a string constant: "this is a string"
Character: 'blue bgDark' # a character constant: 'c', '\n'
Boolean: 'blue bgDark' # a boolean constant: TRUE, false
Number: 'blue bgDark' # a number constant: 234, 0xff 
Float: 'blue bgDark' # a floating point constant: 2.3e10
# IDENTIFIER SYNTAX
Identifier: 'purpleDark' # any variable name
Function: 'greenDark' # function name (also: methods for classes)
# STATEMENT SYNTAX
Statement: 'grayDark' # any statement
Conditional: '' # if, then, else, endif, switch, etc.
Repeat: '' # for, do, while, etc.
Label: '' # case, default, etc.
Operator: 'pink' # "sizeof", "+", "*", etc.
Keyword: 'purpleDark' # any other keyword
Exception: 'purpleDark' # try, catch, throw
# PREPROCESSOR SYNTAX
PreProc: 'blue' # generic Preprocessor
Include: '' # preprocessor #include
Define: '' # preprocessor #define
Macro: '' # same as Define
PreCondit: '' # preprocessor #if, #else, #endif, etc.
# TYPE SYNTAX
Type: 'purpleDark' # int, long, char, etc.
StorageClass: 'purple' # static, register, volatile, etc.
Structure: 'purple' # struct, union, enum, etc.
Typedef: 'purple' # A typedef
# SPECIAL SYNTAX
Special: 'purple - b' # any special symbol
SpecialChar: 'textEmphasis' # special character in a constant ("\n")
Tag: 'textEmphasis' # you can use CTRL-] on this
Delimiter: 'textEmphasis grayLight' # character that needs attention ({ } in sh, etc.)
SpecialComment: 'textEmphasis' # special things in a comment (doxygen param, etc.)
Debug: 'textEmphasis' # debugging statements
Underlined: '- - u' # text that stands out, HTML links
Ignore: '' # left blank, hidden
Error: 'red white' # any erroneous construct
Todo: 'redLight - b' # anything needing attention; TODO FIXME and XXX
